### ISSUE TITLE
Error after running run.sh

### ISSUE THREAD

**Issue by BramDo** [aThorp96/bb84#1]
This is a great application for simulaqron. I have this bb85 appliacation installed on top of version 3.0.4 simulaqron. After running run.sh it gives an error:
AttributeError: 'BitVector' object has no attribute 'to_bytes'
What might be the problem?
Regards, Bram

**Comment by aThorp96** [comment]
Ah, Alice.py and Bob.py were not updated, and my documentation was lacking here. `encrypt` and `decrypt` expect the key to be an int. The keygen methods both return a BitVector object at the moment. Feel free to submit a PR with some typechecking if you're participating in Hacktoberfest. I'll probably get around to fixing it at some point otherwise

**Comment by aThorp96** [comment]
I just fixed the issue. `run.sh` actually was not correctly named anyway, as it ran the algorithm 1000 times to get some statistics. It was mostly a personal script. I've added `demo.sh` which I believe has the functionality you'd expect. I went ahead and added some type checking and conversion to the encrypt and decrypt methods. Thanks for letting me know about the issue!
